export const GET_APPSTATE = "GET_APPSTATE";
export const GET_APPSTATE_SUCCESS = "GET_APPSTATE_SUCCESS";
export const GET_APPSTATE_FAILED = "GET_APPSTATE_FAILED";

// export const LOGIN = 'LOGIN';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAILED = 'LOGIN_FAILED';

// export const LOGOUT = 'LOGOUT';
// export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// export const UPDATE_APPSTATE = 'UPDATE_APPSTATE';
// export const CHANGE_APP_LANGUAGE = 'CHANGE_APP_LANGUAGE';

export const GET_FORM_ELEMENTS = "GET_FORM_ELEMENTS";
export const GET_FORM_ELEMENTS_SUCCESS = "GET_FORM_ELEMENTS_SUCCESS";
export const GET_FORM_ELEMENTS_FAILED = "GET_FORM_ELEMENTS_FAILED";

export const GET_REGISTRATIONS = "GET_REGISTRATIONS";
export const GET_REGISTRATIONS_SUCCESS = "GET_REGISTRATIONS_SUCCESS";
export const GET_REGISTRATIONS_FAILED = "GET_REGISTRATIONS_FAILED";

export const CREATE_REGISTRATION = "CREATE_REGISTRATION";
export const CREATE_REGISTRATION_SUCCESS = "CREATE_REGISTRATION_SUCCESS";
export const CREATE_REGISTRATION_FAILED = "CREATE_REGISTRATION_FAILED";

// export const UPDATE_REGISTRATION = "UPDATE_REGISTRATION";
// export const UPDATE_REGISTRATION_SUCCESS = "UPDATE_REGISTRATION_SUCCESS";
// export const UPDATE_REGISTRATION_FAILED = "UPDATE_REGISTRATION_FAILED";

// export const DELETE_REGISTRATION = "DELETE_REGISTRATION";
// export const DELETE_REGISTRATION_SUCCESS = "DELETE_REGISTRATION_SUCCESS";
// export const DELETE_REGISTRATION_FAILED = "DELETE_REGISTRATION_FAILED";

export const GET_OCCUPIED_ROOMS = "GET_OCCUPIED_ROOMS";
export const GET_OCCUPIED_ROOMS_SUCCESS = "GET_OCCUPIED_ROOMS_SUCCESS";
export const GET_OCCUPIED_ROOMS_FAILED = "GET_OCCUPIED_ROOMS_FAILED";